### ISSUE TITLE
angular-jquery-timepicker not working with brunch

### ISSUE THREAD

**Issue by lex-em** [Recras/angular-jquery-timepicker#38]
I have installed angular-jquery-timepicker (in bower.json: "angular-jquery-timepicker": "^0.11.0")

When I trying to run brunch I get the following error:
`<>>brunch b
<>\node_modules\read-components\index.js:226
        throw new Error('Dependency "' + depName + '" is not present in the list of deps [' + names + ']. Specify correct dependency in ' + type + '.json or contact package author.');
        ^

Error: Dependency "jquery-timepicker-jt" is not present in the list of deps [angular, angular-animate, angular-cookies, angular-loader, angular-resource, angular-route, angular-sanitize, angular-bootstrap, leaflet, Leaflet.extra-markers, angular-leaflet, bootst
rap, animate.css, restangular, font-awesome, malihu-custom-scrollbar-plugin, angular-ui-select, flag-icon-css, angular-smart-table, angular-moment, angular-jquery-timepicker, jt.timepicker, jquery, lodash, jquery-mousewheel, moment, jt.timepicker]. Specify correct dependency in bower.json or contact package author.
  at<>\node_modules\read-components\index.js:226:15
  at Array.forEach (native)
  at setLevel (<>\node_modules\read-components\index.js:206:10)
  at Array.forEach (native)
  at setSortingLevels (<>\node_modules\read-components\index.js:231:12)
  at sortPackages (<>\node_modules\read-components\index.js:237:10)
  at <>\node_modules\read-components\index.js:267:20
  at <>\node_modules\read-components\index.js:180:9
  at <>\node_modules\async-each\index.js:24:44
  at <>\node_modules\read-components\index.js:134:7
  at <>\node_modules\read-components\index.js:81:7
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
`

**Comment by lex-em** [comment]
close :) bower.json overrides:
`    "jquery-timepicker-jt": {
      "name": "jquery-timepicker-jt"
    }`
